### ISSUE TITLE
Point Z not supported

### ISSUE THREAD

**Issue by KindCoder-no** [vannieuwenhovej/wkt-geometry-plotter#5]
**Is your feature request related to a problem? Please describe.**
Hi. When trying to import POINT Z() i just get an error that the string is not valid WKT

**Describe the solution you'd like**
Add support for POINT Z

**Additional context**
This is an example Point Z string: POINT Z(301977.635 7056848.876 69.186)

**Comment by vannieuwenhovej** [comment]
Hi @KindCoder-no , thank you for your issue.

Unfortunately, POINT Z and other 3-dimensional geometries are not supported on the 2-dimensional map.

**Comment by KindCoder-no** [comment]
Thanks for your response. Do you know of any method to concert Point Z to lat/lon or normal Point?

**Comment by KindCoder-no** [comment]
I think it is Z coordinate (never heard of)

**Comment by KindCoder-no** [comment]
Dont know coordinate system

**Comment by vannieuwenhovej** [comment]
> Dont know coordinate system

> ![image](https://user-images.githubusercontent.com/40148297/245595280-f890daf7-f15b-4697-936e-254cbf3a08a8.png)



In your screenshot the numbers are low "10","20", etc. This is probably in EPSG:4326, generally called WGS84. Your point however has large numbers and indicates a different EPSG coordinate system, like for example EPSG:31370, generally called Lambert72 is Belgium's coordinate system.

Try to convert it to WGS84 coordinates and I can help you further. I also believe that if you just remove the third coordinate of the POINT Z structure, you will just become a normal wkt POINT.

**Comment by KindCoder-no** [comment]
I tried removing the last digit. But the point was not correct placed. But i wil try the coordinate system you mentioned

**Comment by KindCoder-no** [comment]
The Lanbert72 coordinate system did not work. The coordinate is in norway if that helps you?

**Comment by KindCoder-no** [comment]
Managed to get the correct coordinates using this tool: https://www.kartverket.no/til-lands/posisjon/transformere-koordinater-enkeltvis

**Comment by vannieuwenhovej** [comment]
Good, now convert the coordinates to WGS84 (EPSG:4326) and try to place the `POINT` onto the map with the last part removed.
