### ISSUE TITLE
If a geojson file is uploaded with different colors for the geometry use those colors.

### ISSUE THREAD

**Issue by dansmith-danrens** [vannieuwenhovej/wkt-geometry-plotter#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dansmith-danrens** [comment]
Here is an example:

{
	"type": "FeatureCollection",
	"features": [{
		"type": "Feature",
		"properties": {
			"stroke": "#555555",
			"stroke-width": 2,
			"stroke-opacity": 1,
			"fill": "#00aa22",
			"fill-opacity": 0.5
		},
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[-76.97021484375,
						40.17887331434696
					],
					[-74.02587890625,
						39.842286020743394
					],
					[-73.4326171875,
						41.713930073371294
					],
					[-76.79443359375,
						41.94314874732696
					],
					[-76.97021484375,
						40.17887331434696
					]
				]
			]
		}
	}]
}

**Comment by vannieuwenhovej** [comment]
Hi @dansmith-danrens! Thank you for your using the tool. 

This is a feature I will implement. I will notify you when the feature is implemented.

**Comment by vannieuwenhovej** [comment]
Hi @dansmith-danrens ! Great news!

Your feature has been implemented. You can now plot geojsons with custom given properties like color. 
Test your geometry out on [https://geometrymapper.com](https://geometrymapper.com)!

**Comment by vannieuwenhovej** [comment]
Hi @dansmith-danrens ! Great news!

Your feature has been implemented. You can now plot geojsons with custom given properties like color.
Test your geometry out on [https://geometrymapper.com](https://geometrymapper.com)!
